// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkhpulnmtmswnshhfzzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRraHB1bG5tdG1zd25zaGhmenpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDU0MTMsImV4cCI6MjA3NDAyMTQxM30.s0UT5Rl64KtLzNYtWf1wEWG121IyxbnW-op51bRtOT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});